### ISSUE TITLE
CentOS 7 Login-Server is missing

### ISSUE THREAD

**Issue by ecdarreola** [Normynator/roCORD#32]
**Describe the bug**
Login-server is missing after completing make install.

**To Reproduce**
1. Install everything as stated in the installation manual for CentOS7
2. Compiling process shows login-server (see attached image below)
![image](https://user-images.githubusercontent.com/48939874/56568927-9058c480-65ea-11e9-81e3-acaebc5bfbdd.png)
3. After make install is finished it says it is missing. Yes its true that it is missing since it cannot be found anymore.  Notice that only char-server and map-server is available on the main directory. (see attached imaged below)
![image](https://user-images.githubusercontent.com/48939874/56568987-b2524700-65ea-11e9-9d6e-01b399145435.png)
4. Replication ended.

**Expected behavior**
Expected Behavior: Login-server should not be missing after recompiling. This works perfectly fine on Debian 9 System

**Screenshots**
Screenshots are as posted in the replication steps

**System(please complete the following information):**
 - OS: CentOS 7 (GCP)
![image](https://user-images.githubusercontent.com/48939874/56569129-ffceb400-65ea-11e9-8620-8d632d2436c4.png)
 - Git hash: Latest rAthena Version

**Comment by Normynator** [comment]
Don’t run make install, try only make

**Comment by ecdarreola** [comment]
@Normynator worked perfectly! Thanks! the guide should have a caveat for such error.
